### ISSUE TITLE
What's a Middleware

### ISSUE THREAD

**Issue by marcj** [php-pm/php-pm-psr7#1]
A explanation what  `Your\\App\\Middleware` is, how it looks and how to write it in `vendor/bin/ppm start --bridge=PHPPM\\Psr7\\Psr7Bridge --bootstrap=Your\\App\\Middleware` would be quiet handy :)

**Comment by Lewiscowles1986** [comment]
Also on the middleware; where is the call to `$next` if this is a middleware?
What is the cost of transforming from a react request & response to a PSR-7 one per request?

**Comment by franzliedke** [comment]
@marcj Good point, done. I hope it's understandable.

@Lewiscowles1986 `$next` can be null, which it is in this case.

As for cost, I haven't benchmarked it, but as it's a very straightforward operation, more or less only mapping fields from one implementation to the other, it shouldn't be costly at all - especially when compared to the bootstrap process that you save.
