### ISSUE TITLE
Empty ReactRequest body makes POST unusable

### ISSUE THREAD

**Issue by fiskWasTaken** [php-pm/php-pm-psr7#3]
An oversight on the master branch of React HTTP means that a request body is never set if it exists:

https://github.com/reactphp/http/blob/master/src/RequestParser.php#L151

Since a typical POST request fulfils the criteria to hit one of the two return statements in that function, that line is never reached and the body (string... one of the [current PRs](https://github.com/reactphp/http/pull/41) is implementing actual streams) is always empty. Moving that line to the top of the method made simple requests work as expected.

This is a problem for the bridge because a request body stream is part of the PSR-7 standard -- getPost() et al is not. Until the upcoming streaming request body PR is merged, how should we proceed in the meantime?

**Comment by franzliedke** [comment]
Hmm... can we get this fixed before that other PR is merged? @WyriHaximus

**Comment by steverhoades** [comment]
Not entirely sure where your issue is but I ran into something similar with a middleware library I was tooling around with for ReactPHP.  you can see how I fixed this here:
https://github.com/steverhoades/expressive-async/blob/master/src/RequestParser.php

**Comment by franzliedke** [comment]
Looks like reactphp/http has seen quite a bit of overhaul since this issue was created (oops).

Does that mean this is no longer a problem? @Fiskie @WyriHaximus

**Comment by franzliedke** [comment]
Closing, as the code looks fine now, as far as I can tell.
