### ISSUE TITLE
Refactoring towards psr7 

### ISSUE THREAD

**Issue by andig** [php-pm/php-pm-psr7#8]
@franzliedke I've been wondering if it would help us any reduce amount of code using https://github.com/phly/react2psr7 (noticed your comment there) and was also wondering if we could/should then make https://github.com/php-pm/php-pm-psr7 and therefore psr7 the basis of all other bridges, most importantly https://github.com/php-pm/php-pm-httpkernel

What do you think?

**Comment by franzliedke** [comment]
Yeah, I think it's a good idea to use react2psr7 directly. (In fact, I may have a local branch lying around somewhere that attempts to use it.)

@andig Are you interested in sending a PR?

**Comment by andig** [comment]
Stuck in dependency hell:

	➜  vz git:(next) ✗ composer require php-pm/psr7-adapter react/http:dev-master php-pm/php-pm:dev-master
	Using version dev-master for php-pm/psr7-adapter
	./composer.json has been updated
	Loading composer repositories with package information
	Updating dependencies (including require-dev)
	Your requirements could not be resolved to an installable set of packages.

	  Problem 1
	    - phly/react2psr7 0.1.1 requires react/http ^0.5@dev -> satisfiable by react/http[0.5.x-dev].
	    - phly/react2psr7 0.1.1 requires react/http ^0.5@dev -> satisfiable by react/http[0.5.x-dev].
	    - phly/react2psr7 0.1.1 requires react/http ^0.5@dev -> satisfiable by react/http[0.5.x-dev].
	    - Can only install one of: react/http[dev-master, 0.5.x-dev].
	    - Can only install one of: react/http[dev-master, 0.5.x-dev].
	    - Can only install one of: react/http[dev-master, 0.5.x-dev].
	    - Installation request for react/http dev-master -> satisfiable by react/http[dev-master].
	    - Installation request for phly/react2psr7 ^0.1.1 -> satisfiable by phly/react2psr7[0.1.1].

I'll probably need to vcs-alias first and then take it from there. Will look into this but (much) later :/

**Comment by franzliedke** [comment]
Ah yes, I remember. Thanks for trying!

**Comment by andig** [comment]
> Ah yes, I remember. Thanks for trying!

Giving up after 3 hours of aggressive hacking. I don't see how react2psr7 can work in its current state regardless which target branch I'm mapping it to. The `getFiles()`, `getBody()` and other functions of the react request don't exist whereever I look for them.

Suggesting to keep this issue open until sometime in the next 10 years when the react mists have cleared (https://github.com/phly/react2psr7/issues/2)

**Comment by franzliedke** [comment]
Hey @andig, look what I found: https://github.com/phps-cans/bridge.psr7-to-reactphp :)

**Comment by andig** [comment]
Mhhm. Looks like an inbetween thingy on first quick look? And.... it does have exactly the same problems as phly :/

**Comment by franzliedke** [comment]
react/http just released v0.5.0: https://github.com/reactphp/http/releases/tag/v0.5.0 :)

**Comment by andig** [comment]
Woah, really? Yesterday we weren't eveb on 0.4.4?

Viele Grüße,
Andreas

**Comment by andig** [comment]
In terms of utilization I assume we'll need to wait for 0.8 for the body parsers. Didn't look into how/if psr7 compliance in 0.7 would be usable without it, especially for the httpkernel bridge. 
Mid term I'd like to look into replacing the react/httpkernel bridge with react psr7/psr7 http kernel standard bridges to reduce our custom code?

**Comment by maciejmrozinski** [comment]
https://github.com/php-pm/php-pm-psr7/pull/11

**Comment by andig** [comment]
Superseded by https://github.com/php-pm/php-pm/pull/278
